src/objects/Chat_Message__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Chat  Messages</relationshipLabel>
        <relationshipName>Chat_Messages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Volleyball_Event__c</fullName>
        <label>Volleyball Event</label>
        <referenceTo>Volleyball_Event__c</referenceTo>
        <relationshipLabel>Chat  Messages</relationshipLabel>
        <relationshipName>Chat_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat  Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Volleyball_Event__c.object
<CustomObject>
    <label>Volleyball Event</label>
    <nameField>
        <displayFormat>VE-{0000}</displayFormat>
        <label>Volleyball Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volleyball Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChatController.cls
public class ChatController {
    public Chat_Message__c chatMessage {get ;set;}
    public List<Chat_Message__c> chatMessages {
        get {
            if(chatMessages == null) {
                retrieveMessages();
            }
            return chatMessages;
        }
        set;
    }
    public String playerName {get;set;}
    public Id eventId {get;set;}
    public Id playerId {get;set;}

    public void sendChatMessage() {
        chatMessage.Text__c = chatMessage.Text__c.replace('\n', '<br>');
        insert chatMessage;
        retrieveMessages();
    }

    private void retrieveMessages() {
        chatMessages = [SELECT Text__c, Player__r.Name, CreatedDate FROM Chat_Message__c
        WHERE Volleyball_Event__c = :eventId ORDER BY CreatedDate];
        chatMessage = new Chat_Message__c(Player__c = playerId, Volleyball_Event__c = eventId);
    }
}