src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Player_Id__c</fullName>
        <label>Player Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Player_Name__c</fullName>
        <label>Player Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <label>StackTrace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Logger.cls
public class Logger {


    public static PageReference log(Exception e) {
        return log(e, null);
    }

    public static PageReference log(Exception e, Id eventId) {
        insert new Log__c(
                Error__c = e.getMessage(),
                StackTrace__c = e.getStackTraceString(),
                Player_Name__c = getPlayerName(),
                Player_Id__c = getPlayerId(),
                Password__c = getPassword(),
                Event_Id__c = eventId
        );
        return Page.VolleyballHome;
    }

    public static String getPlayerName() {
        return (String)ApexPages.currentPage().getCookies().get('playerName').getValue();
    }

    public static String getPlayerId() {
        return (String)ApexPages.currentPage().getCookies().get('playerId').getValue();
    }

    public static String getPassword() {
        return (String)ApexPages.currentPage().getCookies().get('pass').getValue();
    }
}