src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player_Presence__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Volleyball_Event__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Player_Presences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Going__c</fullName>
        <formula>IF(ISPICKVAL(Choice_Status__c, &quot;Going&quot;), IMAGE(&quot;https://login.salesforce.com/logos/Standard/task/logo.svg&quot;, &quot;Green&quot;, 30, 30),
IMAGE(&quot;https://login.salesforce.com/logos/Custom/Bottle_Red/logo.png&quot;, &quot;Red&quot;, 30, 30))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Going</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Player Presences</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Player Presence</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Player Presence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volleyball__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Volleyball</label>
</CustomObject>

src/objects/Volleyball_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Volleyball Event</label>
    <nameField>
        <displayFormat>VE-{0000}</displayFormat>
        <label>Volleyball Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volleyball Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewEventController.cls
public class ViewEventController {
    public List<Player_Presence__c> players {get;set;}
    public String playerName {get;set;}

    private Id eventId;
    private Volleyball_Event__c event;
    private Id playerId;
    private String password;

    public ViewEventController(ApexPages.StandardController sc) {
        event = (Volleyball_Event__c)sc.getRecord();
        playerId = (String)ApexPages.currentPage().getCookies().get('playerId').getValue();
        playerName = (String)ApexPages.currentPage().getCookies().get('playerName').getValue();
        players = [SELECT Player__r.Name, Is_Going__c FROM Player_Presence__c WHERE Event__c = :event.Id
                   ORDER BY Is_Going__c DESC, Player__r.Name];
        password = (String)ApexPages.currentPage().getCookies().get('pass').getValue();
    }

    public Boolean getIsAuthorized() {
        return password == Volleyball__c.getOrgDefaults().Password__c;
    }

    public PageReference toCalendar() {
        PageReference calendar = Page.Calendar;
        Cookie player = new Cookie('playerId', playerId, null, -1, false);
        Cookie pass = new Cookie('pass', password, null, -1, false);
        Cookie evtDate = new Cookie('date', String.valueOf(event.Date__c.toStartOfWeek()), null, -1, false);
        calendar.setCookies(new Cookie[] {player, pass, evtDate});
        return calendar;
    }

    public PageReference saveEvent() {
        update event;
        return toCalendar();
    }

    public PageReference deleteEvent() {
        delete new Volleyball_Event__c (Id = event.Id);
        return toCalendar();
    }

    public PageReference cloneEvent() {
        Volleyball_Event__c clone = event.clone();
        insert clone;
        return redirectToEvent(clone.Id, true);
    }

    public PageReference addMessage() {
        if (ApexPages.currentPage().getParameters().get('clone') != null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, 'Cloned successfully!'));
        }
        return null;
    }

    private PageReference redirectToEvent(Id eventId, Boolean clone) {
        PageReference pg = Page.ViewEvent;
        Cookie player = new Cookie('playerId', playerId, null, -1, false);
        Cookie pass = new Cookie('pass', password, null, -1, false);
        pg.setCookies(new Cookie[] {player, pass});
        pg.getParameters().put('id', eventId);
        pg.setRedirect(true);
        if (clone) {
            pg.getParameters().put('clone', '1');
        }
        return pg;
    }
}