src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player_Presence__c.object
<CustomObject>
    <fields>
        <fullName>Choice_Status__c</fullName>
        <label>Choice Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Going</fullName>
                </value>
                <value>
                    <fullName>Not going</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Volleyball_Event__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Player_Presences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Player Presences</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Player Presence</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Player Presence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volleyball__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Default_Location__c</fullName>
        <label>Default Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Time__c</fullName>
        <label>Default Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Volleyball</label>
</CustomObject>

src/objects/Volleyball_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                    <default>true</default>
                    <label>Training</label>
                </value>
                <value>
                    <fullName>Match</fullName>
                </value>
                <value>
                    <fullName>Beer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>Time</type>
    </fields>
    <label>Volleyball Event</label>
    <nameField>
        <displayFormat>VE-{0000}</displayFormat>
        <label>Volleyball Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volleyball Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CalendarController.cls
public class CalendarController {
    public List<DayEvents> days {get; set;}
    public Date startOfWeekDate {get; set;}
    public Id playerId {get; set;}
    public String playerName {get; set;}
    private String password;

    public Id cancelChoice {get; set;}
    public Id eventChoiceId {get; set;}
    public String eventChoiceResult {get; set;}

    public CalendarController() {
        if (startOfWeekDate == null && ApexPages.currentPage().getCookies().get('date') != null
                                    && String.isNotBlank(ApexPages.currentPage().getCookies().get('date').getValue())) {
            startOfWeekDate = Date.valueOf(ApexPages.currentPage().getCookies().get('date').getValue());
        } else {
            startOfWeekDate = Date.today().toStartOfWeek();
        }
        playerId = (String)ApexPages.currentPage().getCookies().get('playerId').getValue();
        playerName = (String)ApexPages.currentPage().getCookies().get('playerName').getValue();
        password = (String)ApexPages.currentPage().getCookies().get('pass').getValue();

        initWeek();
    }

    public PageReference generateTrainings() {
        Time defaultTime = Volleyball__c.getOrgDefaults().Default_Time__c.time();
        insert new Volleyball_Event__c[] {
                new Volleyball_Event__c(
                        Location__c = Volleyball__c.getOrgDefaults().Default_Location__c,
                        Time__c = defaultTime,
                        Event_Type__c = 'Training',
                        Date__c = startOfWeekDate
                ),
                new Volleyball_Event__c(
                        Location__c = Volleyball__c.getOrgDefaults().Default_Location__c,
                        Time__c = defaultTime,
                        Event_Type__c = 'Training',
                        Date__c = startOfWeekDate.addDays(4)
                )
        };
        initWeek();
        return null;
    }

    public PageReference deleteEvent() {
        delete new Volleyball_Event__c (Id = eventChoiceId);
        return null;
    }

    public Boolean getIsAuthorized() {
        return password == Volleyball__c.getOrgDefaults().Password__c;
    }

    public PageReference nextWeek() {
        startOfWeekDate = startOfWeekDate.addDays(7);
        initWeek();
        return null;
    }

    public PageReference prevWeek() {
        startOfWeekDate = startOfWeekDate.addDays(-7);
        initWeek();
        return null;
    }

    public PageReference currentWeek() {
        startOfWeekDate = Date.today().toStartOfWeek();
        initWeek();
        return null;
    }

    public PageReference viewEvent() {
        PageReference pg = Page.ViewEvent;
        pg.getParameters().put('Id', eventChoiceId);
        Cookie playerId = new Cookie('playerId', playerId, null, -1, false);
        Cookie playerName = new Cookie('playerName', playerName, null, -1, false);
        Cookie pass = new Cookie('pass', password, null, -1, false);
        pg.setCookies(new Cookie[] {playerId, playerName, pass});
        pg.setRedirect(true);
        return pg;
    }

    public PageReference cancelChoice() {
        delete new Player_Presence__c(Id = cancelChoice);
        return null;
    }

    public PageReference makeChoice() {
        insert new Player_Presence__c(Player__c = playerId,
                Event__c = eventChoiceId,
                Choice_Status__c = eventChoiceResult);
        return null;
    }

    private void initWeek() {
        PageReference calendar = ApexPages.currentPage();
        Cookie evtDate = new Cookie('date', String.valueOf(startOfWeekDate), null, -1, false);
        calendar.setCookies(new Cookie[] {evtDate});
        days = DayEventsFactory.getInstance(playerId).getDays(startOfWeekDate);
    }
}