src/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Player_Presence__c.object
<CustomObject>
    <fields>
        <fullName>Choice_Status__c</fullName>
        <label>Choice Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Going</fullName>
                </value>
                <value>
                    <fullName>Not going</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Volleyball_Event__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Player_Presences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>Player Presences</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Player Presence</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Player Presence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Presences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volleyball_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                    <default>true</default>
                    <label>Training</label>
                </value>
                <value>
                    <fullName>Match</fullName>
                </value>
                <value>
                    <fullName>Beer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>Time</type>
    </fields>
    <label>Volleyball Event</label>
    <nameField>
        <displayFormat>VE-{0000}</displayFormat>
        <label>Volleyball Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volleyball Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DayEventsFactory.cls
public with sharing class DayEventsFactory {
    private Map<Date, DayEvents> weekDays;
    private Date weekDate;
    private Id playerId;

    private DayEventsFactory(Id playerId) {
        this.playerId = playerId;
        weekDays = new Map<Date, DayEvents>();
    }

    public List<DayEvents> getDays(Date startDate) {
        setWeekDate(startDate);

        for (Volleyball_Event__c event : [SELECT Id, Date__c, Event_Type__c, Location__c, Time__c, Note__c,
                                (SELECT Id, Choice_Status__c FROM Player_Presences__r WHERE Player__c = :playerId)
                                          FROM Volleyball_Event__c
                                          WHERE Date__c >= :startDate
                                          AND Date__c <= :startDate.addDays(6)
                                          ORDER BY Date__c, Time__c]) {
            weekDays.get(event.Date__c).events.add(event);
        }

        return weekDays.values();
    }

    private void setWeekDate(Date startDate) {
        if (weekDate == null || weekDate != startDate) {
            weekDays.clear();
            for (Integer i=0; i<7; i++) {
                weekDays.put(startDate.addDays(i), new DayEvents(startDate.addDays(i)));
            }
            weekDate = startDate;
        } else {
            for (DayEvents day : weekDays.values()) {
                day.events.clear();
            }
        }
    }

    private static DayEventsFactory instance;
    public static DayEventsFactory getInstance(Id playerId) {
        if (instance == null || playerId != instance.playerId) {
            instance = new DayEventsFactory(playerId);
        }
        return instance;
    }
}